name: Run build on push
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1,3,5"
  workflow_dispatch:
env:
  VBUILD_UNIT_TESTS: true
  CONAN_VER: 1.51.3
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: src/python-bindings/pips
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install -U wheel setuptools auditwheel patchelf pybind11
          pip wheel . --verbose -w dist
          auditwheel repair dist/opentdf*.whl --plat manylinux2014_x86_64

      - name: Build wheels for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pip install -U wheel setuptools
          python setup.py bdist_wheel -d wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl