name: Run build on push
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1,3,5"
  workflow_dispatch:
env:
  VBUILD_UNIT_TESTS: true
  CONAN_VER: 1.51.3
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - PLAT: manylinux2014_x86_64
            DOCKER_IMAGE: quay.io/pypa/manylinux2014_x86_64
    env:
      PLAT: ${{ matrix.MANYLINUX_VER }}
      DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
      PY_VER: ${{ matrix.PY_VER }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/install_req.sh -e PLAT=$PLAT
      - name: Result
        run: ls -al wheelhouse/
