name: Run build on push
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1,3,5"
env:
  VBUILD_UNIT_TESTS: true
  CONAN_VER: 1.51.3
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: src/python-bindings/pips

    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          - os: windows-2019-py38-amd64
            python: 38
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest-py39-amd64
            python: 39
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest-py310-amd64
            python: 310
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest-py38-win32
            python: 38
            bitness: 32
            platform_id: win32
          - os: windows-latest-py39-win32
            python: 39
            bitness: 32
            platform_id: win32

          - os: ubuntu-latest-py38-x86
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest-py39-x86
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest-py310-x86
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          - os: macos-latest-py38-x86
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          - os: macos-latest-py39-x86
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          - os: macos-latest-py310-x86
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-latest-py38-arm64
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest-py39-arm64
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest-py310-arm64
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_TEST_SKIP: "*-macosx_arm64"
          CIBW_BUILD_VERBOSITY: 1
        run: bash build_tools/build_wheels.sh
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl