name: Run build
on:
  push:
    branches:
      - wheel-experiment
  schedule:
    - cron: "0 7 * * 1,3,5"
  workflow_dispatch:
env:
  VBUILD_UNIT_TESTS: false
  CONAN_VER: 1.59.0
jobs:
 build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v3

    # - uses: pypa/cibuildwheel@v1.12.0
    #   env:
    #     # Python 2.7 on Windows requires a workaround for C++11 support,
    #     # built separately below
    #     CIBW_SKIP: cp27-win*
    #     CIBW_ARCHS_MACOS: auto universal2

    # Used to host cibuildwheel
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.12.3 wheel==0.40.0 pybind11==2.10.3 twine==4.0.2 --force

    - name: Build wheels
      run: |
        cd src/python-bindings/pips/
        python -m cibuildwheel --output-dir wheelhouse
      # to supply options, put them in 'env', like:
      # env:
      #   CIBW_SOME_OPTION: value
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_BEFORE_BUILD_MACOS: ../../../build-all.sh
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
